import './js/header';
import './js/burger-menu';
import './js/theme-toggle';
import './js/user-bar';
import './js/support';
import './js/swiper';
import './js/shoping-list-render';
import './js/loader';
import './js/modal_window';